{% set name = "cf_xarray" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23833bce5ddffc31ec95258c82a62c848c15332696d91abbf960a4325bc6accb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
    - xarray
  run:
    - python >=3.9
    - xarray

test:
  imports:
    - cf_xarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/cf-xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight convenience wrapper for using CF attributes on xarray objects.

  description: |
    A lightweight convenience wrapper for using CF attributes on xarray objects..
  doc_url: https://cf-xarray.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/cf-xarray

extra:
  recipe-maintainers:
    - dcherian
    - malmans2
    - aulemahal
    - kthyng
