{% set python_min = "3.11" %}
{% set name = "cf_xarray" %}
{% set version = "0.10.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbb6f6db9cb98a75554af916f1c293a041d30e54f60c0cf6c509cf4d55b5af7f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
    - xarray >=2023.09.0
  run:
    - python >={{ python_min }}
    - xarray >=2023.09.0

test:
  imports:
    - cf_xarray
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

outputs:
  - name: cf_xarray
  - name: cf-xarray
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("cf_xarray", max_pin="x.x.x") }}
        - python >={{ python_min }}
    test:
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
      imports:
        - cf_xarray

about:
  home: https://github.com/xarray-contrib/cf-xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight convenience wrapper for using CF attributes on xarray objects.

  description: |
    A lightweight convenience wrapper for using CF attributes on xarray objects..
  doc_url: https://cf-xarray.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/cf-xarray

extra:
  recipe-maintainers:
    - dcherian
    - malmans2
    - aulemahal
    - kthyng
